name: create kops cluster

on:
    workflow_dispatch:
      inputs:
        cluster_name:
          description: 'name to cluster'
          required: true
          default: 'warning'
          type: choice
          options:
          - kds.com
        kops_state_store:
          description: 'bucket to use'
          required: true
          type: choice
          option:
           - fusion1-state-tf
        environment:
          description: 'Environment to run tests against'
          type: choice
          required: true
          option:
           - dev
           - stg
           - prd
jobs:
    print-tag:
      runs-on: ubuntu-latest
      if:  ${{ inputs.print_tags }} 
      steps:
        - name: Print the input tag to STDOUT
          run: echo  The tags are ${{ inputs.tags }} 